
module.exports = {
  LITERAL: Symbol("LITERAL"),
  WHITESPACE: Symbol("WHITESPACE"),
  BREAK: Symbol("BREAK"),
  TEMPLATE_STRING: Symbol("TEMPLATE_STRING"),
  TEMPLATE_STRING_LITERAL: Symbol('TEMPLATE_STRING_LITERAL'),
  TEMPLATE_STRING_INTERPRETATION: Symbol('TEMPLATE_STRING_INTERPRETATION'),
  ARRAY: Symbol('ARRAY'),
  FUNCTION_SIGNATURE: Symbol('FUNCTION_SIGNATURE'),
  STATEMENT_FUNCTION: Symbol('STATEMENT_FUNCTION'),
  UNARY_OVERLOAD: Symbol('UNARY_OVERLOAD'),
  LEFT_INFIX_OVERLOAD: Symbol('LEFT_INFIX_OVERLOAD'),
  RIGHT_INFIX_OVERLOAD: Symbol('RIGHT_INFIX_OVERLOAD'),
  STRUCT: Symbol("STRUCT"),
  REFERENCE: Symbol("REFERENCE"),
  TYPE_REFERENCE: Symbol("TYPE_REFERENCE"), 
}
