
const add = require('./add')
const alias = require('./alias')
const build = require('./build')
const init = require('./init')
const install = require('./install')
const interactive = require('./interactive')
const publish = require('./publish')
const run = require('./run')
const source = require('./source')
const start = require('./start')
const test = require('./test')
const update = require('./update')
const upgrade = require('./upgrade')

module.exports = yargs => yargs
    .command(add)
    .command(alias)
    .command(build)
    .command(init)
    .command(install)
    .command(interactive)
    .command(publish)
    .command(run)
    .command(source)
    .command(start)
    .command(test)
    .command(update)
    .command(upgrade)
